apiVersion: v1
kind: Service
metadata:
  name: priti-service
  namespace: priti-web
spec:
  type: NodePort
  selector:
    app: priti
  ports:
    - port: 80         # The port the service exposes inside the cluster
      targetPort: 80    # The port your Pod (Nginx container) is listening on
      nodePort: 32000   # The external port on the Node
      protocol: TCP
