apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginix-web
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 9090         # The port the service exposes inside the cluster
      targetPort: 9090    # The port your Pod (Nginx container) is listening on
      nodePort: 30880   # The external port on the Node
      protocol: TCP
