apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  destination:
    namespace: nginix-web
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/kumardheeraj394/kubernetes.git
    targetRevision: HEAD
    path: .
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
